### ISSUE TITLE
setPortsInUse(new ArrayList<>) - TransportLayer

### ISSUE THREAD

**Issue by Nafruoy** [gswcm/CSCI4310_FA17_P2#5]
Minor issue, if at all. 

JDK 1.7 requires setPortsInUse() in the TransportLayer constructor to pass through a `new ArrayList<Integer>`, but for 1.8, it seems to be fine. 

Don't know if anybody actually has a problem with that. Just thought I'd bring it up.

**Comment by BrandonRix** [comment]
Well since JDK 1.7 is causing issues, it would probably be best to go to 1.8.

**Comment by Nafruoy** [comment]
That's fine. Got 1.8 ready on laptop. Just haven't update jdk for desktop.

**Comment by BrandonRix** [comment]
close #5

**Comment by Nafruoy** [comment]
TransportLayer is using `ArrayList<Integer>` now, so we can consider this closed.
